#!/bin/bash

#define colors
RED='\033[00;31m'
GREEN='\033[00;32m'
YELLOW='\033[00;33m'
BLUE='\033[00;34m'
PURPLE='\033[00;35m'
CYAN='\033[00;36m'
LIGHTGRAY='\033[00;37m'

LRED='\033[01;31m'
LGREEN='\033[01;32m'
LYELLOW='\033[01;33m'
LBLUE='\033[01;34m'
LPURPLE='\033[01;35m'
LCYAN='\033[01;36m'
WHITE='\033[01;37m'

RESET=$(tput sgr0)

hname='@\H'
usr='\u'
nl='\n'
usr_color=${LGREEN}
wrk_dir='\w'

dts=$(date +"%d-%b-%Y %I:%M %p ")

[[ $UID == 0 ]] && usr_color=${RED}


function ret_thing(){
  if [[ $? -eq 0 ]]; then 
    printf  "${LGREEN}* ^_^${RESET}"
  else 
    printf "${RED}x O_o${RESET}"
  fi
}

#export PS1="${LIGHTGRAY}`printf "%${COLUMNS}s\n" "${dts}"`\`ret_thing\`${RESET} \
#${CYAN}|| ${RESET}${usr_color}${usr}${RESET} ${LPURPLE}${hname}${RESET}${CYAN} \
#||${RESET} ${BLUE}${wrk_dir}${RESET} ${LIGHTGRAY}${RESET}${nl} ${CYAN}->${RESET} "

export PS1="${LIGHTGRAY}`printf -vch "%${COLUMNS}s" "${dts}"; printf "%s" "${ch// /-}"`${RESET}\`ret_thing\`${RESET} \
${CYAN}|| ${RESET}${usr_color}${usr}${RESET} ${LPURPLE}${hname}${RESET}${CYAN} \
||${RESET} ${BLUE}${wrk_dir}${RESET} ${LIGHTGRAY}${RESET}${nl} ${CYAN}->${RESET} "